cloudflare_account_id = "4c6fe3566a04f18ddfdeae5831df616d"
domain                = "queercoded.dev"
github_owner          = "queercoded-dev"
github_repo_name      = "queercoded.dev"
production_branch     = "main"
